# Configversion - DO NOT TOUCH!
configversion: 1
######################################################
# Set to true if you want to use items instead of EXP.
useitems: false
# If useitems = true what items should be used?
Item ID: 19
# The name of the item (only relevant for the chat)
Item Name: Sponge
# What is the max Level a player can get?
maxLevel: 25
# In what intervall shall we grant skillponts?
Skillpoints Interval: 5
# How many skillpoints shall we give them?
Skillpoints: 1

Permissions:
    # Whats the name of the Permissions track your levels are on?
    track: level

# Config for the daily login bonus.
DailyExp:
    # Set to true if you want to give players a daily exp bonus on their first login.
    giveDailyExp: false
    # How many EXP should players with lvlup.exp.normal get?
    normalExp: 20
    # How many EXP should players with lvlup.exp.vip get?
    vipExp: 40